version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '13:00'
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:00"
    timezone: "America/New_York"
  labels:
    - "actions"
    - "dependabot"
  assignees:
    - "jeffsays"
  reviewers:
    - "jeffsays"
