language: node_js

branches:
  only:
    - master
  
node_js:
  - node
  - 12
  - 10
  - 8

cache: yarn

script:
  - yarn flow:check
  - yarn flow:annotations
  - yarn flow:coverage
  - yarn jest --coverage
  - yarn codecov
