language: node_js

node_js:
  - node
  - 7
  - 6
  - 5
  - 4

cache: yarn

script: yarn run test:ci

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
