name: Package Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  yarn:
    name: Yarn Lock Changes
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Yarn Lock Changes
        uses: CumulusDS/yarn-lock-changes-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
